### ISSUE TITLE
Compose Migration

### ISSUE THREAD

**Issue by mustafaozhan** [Oztechan/CCC#2001]
```[tasklist]
- [ ] #1505
- [ ] #1610
- [ ] #1622
- [ ] #1592
- [ ] #1626
- [ ] #1971
- [ ] https://github.com/Oztechan/CCC/issues/3413
- [ ] https://github.com/Oztechan/CCC/issues/3419
- [ ] #1514
- [ ] #1516
- [ ] https://github.com/Oztechan/CCC/issues/3422
```
