### ISSUE TITLE
Widget Refactoring

### ISSUE THREAD

**Issue by mustafaozhan** [Oztechan/CCC#2356]
```[tasklist]
### Tasks
- [ ] https://github.com/Oztechan/CCC/issues/2359
- [ ] https://github.com/Oztechan/CCC/issues/2360
- [ ] https://github.com/Oztechan/CCC/issues/2361
- [ ] https://github.com/Oztechan/CCC/issues/2367
- [ ] https://github.com/Oztechan/CCC/issues/2387
- [ ] https://github.com/Oztechan/CCC/issues/2388
- [ ] https://github.com/Oztechan/CCC/issues/2496
- [ ] https://github.com/Oztechan/CCC/issues/2395
- [ ] https://github.com/Oztechan/CCC/issues/2397
- [ ] https://github.com/Oztechan/CCC/issues/2399
- [ ] https://github.com/Oztechan/CCC/issues/2428
- [ ] https://github.com/Oztechan/CCC/issues/2430
- [ ] https://github.com/Oztechan/CCC/issues/2490
- [ ] https://github.com/Oztechan/CCC/issues/2492
- [ ] https://github.com/Oztechan/CCC/issues/2494
```
