### ISSUE TITLE
Fix expected invocations

### ISSUE THREAD

**Issue by mustafaozhan** [Oztechan/CCC#2458]
```[tasklist]
### Tasks
- [ ] https://github.com/Oztechan/CCC/issues/2456
- [ ] https://github.com/Oztechan/CCC/issues/2464
- [ ] https://github.com/Oztechan/CCC/issues/2467
- [ ] https://github.com/Oztechan/CCC/issues/2468
- [ ] https://github.com/Oztechan/CCC/issues/2469
```
