### ISSUE TITLE
Kotlin 1.9.0 Release changes

### ISSUE THREAD

**Issue by mustafaozhan** [Oztechan/CCC#2480]
https://blog.jetbrains.com/kotlin/2023/07/kotlin-1-9-0-released/

```[tasklist]
### Tasks
- [ ] https://github.com/Oztechan/CCC/issues/2481
- [ ] https://github.com/Oztechan/CCC/issues/2482
- [ ] https://github.com/Oztechan/CCC/issues/2483
- [ ] https://github.com/Oztechan/CCC/issues/2504
- [ ] https://github.com/Oztechan/CCC/issues/2498
- [ ] https://github.com/Oztechan/CCC/issues/2501
- [ ] org.gradle.configuration-cache=true
- [ ] check kotlinx-serialization-compiler-plugin
- [ ] https://github.com/Oztechan/CCC/issues/2505
- [ ] https://github.com/Oztechan/CCC/issues/2509
- [ ] https://github.com/Oztechan/CCC/issues/2513
- [x] revert iteration()
```
