### ISSUE TITLE
Use exact versions in third party GitHub Actions

### ISSUE THREAD

**Issue by mustafaozhan** [Oztechan/CCC#2544]
```[tasklist]
### Tasks
- [x] geekyeggo/delete-artifact@v2
- [x] muhamedzeema/appgallery-deply-action@main
- [x] easingthemes/ssh-deploy@main
- [x] voxmedia/github-action-slack-notify-build@v2
- [x] andymckay/cancel-action@0.3
- [x] wzieba/Firebase-Distribution-Github-Action@v1
- [x] codecov/codecov-action@v3
- [x] codacy/codacy-coverage-reporter-action@v1
- [x] sonarsource/sonarcloud-github-action@master
```
