### ISSUE TITLE
Implement Button vibration

### ISSUE THREAD

**Issue by mustafaozhan** [Oztechan/CCC#2585]
https://artandscienceofcoding.com/science/kmm-maximizing-shared-code/
```[tasklist]
### Tasks
- [ ] https://github.com/Oztechan/CCC/issues/2588
- [ ] Vibration effect on iOS
- [ ] Vibration effect on Android
```
