### ISSUE TITLE
Refactor All Views with RootView vs View structure

### ISSUE THREAD

**Issue by mustafaozhan** [Oztechan/CCC#2595]
```[tasklist]
### Tasks
- [ ] https://github.com/Oztechan/CCC/issues/2596
- [ ] https://github.com/Oztechan/CCC/issues/2597
- [ ] https://github.com/Oztechan/CCC/issues/2600
- [ ] https://github.com/Oztechan/CCC/issues/2602
- [ ] https://github.com/Oztechan/CCC/issues/2604
- [ ] https://github.com/Oztechan/CCC/issues/2605
- [ ] https://github.com/Oztechan/CCC/issues/2611
- [ ] https://github.com/Oztechan/CCC/issues/2613
```
