### ISSUE TITLE
Get Rid of public ViewModel methods

### ISSUE THREAD

**Issue by mustafaozhan** [Oztechan/CCC#2636]
```[tasklist]
### Tasks
- [ ] https://github.com/Oztechan/CCC/issues/2637
- [ ] https://github.com/Oztechan/CCC/issues/2639
- [ ] https://github.com/Oztechan/CCC/issues/2642
- [ ] https://github.com/Oztechan/CCC/issues/2643
- [ ] https://github.com/Oztechan/CCC/issues/2644
- [ ] https://github.com/Oztechan/CCC/issues/2645
- [ ] https://github.com/Oztechan/CCC/issues/2650
- [ ] https://github.com/Oztechan/CCC/issues/2652
- [ ] https://github.com/Oztechan/CCC/issues/2654
- [ ] https://github.com/Oztechan/CCC/issues/2663
- [ ] https://github.com/Oztechan/CCC/issues/2665
- [ ] https://github.com/Oztechan/CCC/issues/2667
- [ ] https://github.com/Oztechan/CCC/issues/2669
- [ ] https://github.com/Oztechan/CCC/issues/2713
- [ ] https://github.com/Oztechan/CCC/issues/2711
```
