### ISSUE TITLE
Stabilise Billing

### ISSUE THREAD

**Issue by mustafaozhan** [Oztechan/CCC#2658]
```[tasklist]
### Tasks
- [ ] #2656
- [ ] https://github.com/Oztechan/CCC/issues/2659
- [ ] https://github.com/Oztechan/CCC/issues/2661
- [ ] https://github.com/Oztechan/CCC/issues/2671
```
