### ISSUE TITLE
iOS Navigation Unifying

### ISSUE THREAD

**Issue by mustafaozhan** [Oztechan/CCC#2702]
```[tasklist]
### Tasks
- [ ] https://github.com/Oztechan/CCC/issues/2705
- [ ] https://github.com/Oztechan/CCC/issues/2703
- [ ] https://github.com/Oztechan/CCC/issues/2709
```
