### ISSUE TITLE
Remove Cocoapods from iOS

### ISSUE THREAD

**Issue by mustafaozhan** [Oztechan/CCC#2787]
https://kotlinlang.org/docs/multiplatform-mobile-understand-project-structure.html#ios-application
```[tasklist]
### Tasks
- [ ] https://github.com/Oztechan/CCC/issues/2788
- [ ] https://github.com/Oztechan/CCC/issues/2789
- [ ] https://github.com/Oztechan/CCC/issues/2790
```
