### ISSUE TITLE
API Refactoring

### ISSUE THREAD

**Issue by mustafaozhan** [Oztechan/CCC#2815]
```[tasklist]
### Tasks
- [ ] https://github.com/Oztechan/CCC/issues/2824
- [ ] https://github.com/Oztechan/CCC/issues/2821
- [x] Update Server Java version
- [ ] https://github.com/Oztechan/CCC/issues/2819
- [ ] https://github.com/Oztechan/CCC/issues/2837
- [ ] https://github.com/Oztechan/CCC/issues/2829
- [ ] https://github.com/Oztechan/CCC/issues/2831
- [ ] https://github.com/Oztechan/CCC/issues/2833
- [ ] https://github.com/Oztechan/CCC/issues/2835
- [ ] https://github.com/Oztechan/CCC/issues/2841
- [ ] https://github.com/Oztechan/CCC/issues/2839
```

# In

- FOK
- KID
- SLE
- TVD

# Out

- BTC
- CLF
- CNH
- CUC
- KPW
- MRO
- STD
- SVC
- XAG
- XAU
- XPD
- XPT
