### ISSUE TITLE
Remove experimental multiplatform settings

### ISSUE THREAD

**Issue by mustafaozhan** [Oztechan/CCC#2854]
```[tasklist]
### Tasks
- [ ] https://github.com/Oztechan/CCC/issues/2855
- [ ] https://github.com/Oztechan/CCC/issues/2857
- [ ] https://github.com/Oztechan/CCC/issues/2860
- [ ] https://github.com/Oztechan/CCC/issues/2863
- [ ] https://github.com/Oztechan/CCC/issues/2865
- [ ] https://github.com/Oztechan/CCC/issues/2867
- [ ] https://github.com/Oztechan/CCC/issues/2869
- [ ] https://github.com/Oztechan/CCC/issues/2871
- [ ] https://github.com/Oztechan/CCC/issues/2940
- [ ] https://github.com/Oztechan/CCC/issues/2941
- [ ] https://github.com/Oztechan/CCC/issues/3144
- [ ] https://github.com/Oztechan/CCC/issues/3146
- [ ] https://github.com/Oztechan/CCC/issues/3148
- [ ] https://github.com/Oztechan/CCC/issues/3153
- [ ] https://github.com/Oztechan/CCC/issues/3156
- [ ] https://github.com/Oztechan/CCC/issues/3178
- [ ] https://github.com/Oztechan/CCC/issues/3180
- [ ] https://github.com/Oztechan/CCC/issues/3183
- [ ] https://github.com/Oztechan/CCC/issues/3185
```
