### ISSUE TITLE
Cleanup classpaths

### ISSUE THREAD

**Issue by mustafaozhan** [Oztechan/CCC#2898]
```[tasklist]
### Tasks
- [ ] https://github.com/Oztechan/CCC/issues/2899
- [ ] https://github.com/Oztechan/CCC/issues/2901
- [ ] https://github.com/Oztechan/CCC/issues/2903
- [ ] https://github.com/Oztechan/CCC/issues/2906
- [ ] https://github.com/Oztechan/CCC/issues/2908
- [ ] https://github.com/Oztechan/CCC/issues/2910
- [ ] https://github.com/Oztechan/CCC/issues/2918
- [ ] https://github.com/Oztechan/CCC/issues/2914
- [ ] https://github.com/Oztechan/CCC/issues/2912
- [ ] https://github.com/Oztechan/CCC/issues/2916
- [ ] https://github.com/Oztechan/CCC/issues/2920
- [ ] https://github.com/Oztechan/CCC/issues/2922
- [ ] https://github.com/Oztechan/CCC/issues/2925
- [ ] https://github.com/Oztechan/CCC/issues/2929
- [ ] https://github.com/Oztechan/CCC/issues/2933
- [ ] https://github.com/Oztechan/CCC/issues/2931
```
