### ISSUE TITLE
Ad improvements and privacy

### ISSUE THREAD

**Issue by mustafaozhan** [Oztechan/CCC#3340]
```[tasklist]
### Tasks
- [ ] https://github.com/Oztechan/CCC/issues/3341
- [ ] CMP for iOS App
- [ ] Improve iOS Ad implementation
```
https://developers.google.com/admob/ios/privacy/strategies
