### ISSUE TITLE
Refactor navigation result base change logic

### ISSUE THREAD

**Issue by mustafaozhan** [Oztechan/CCC#3584]
```[tasklist]
### Tasks
- [ ] https://github.com/Oztechan/CCC/issues/3585
- [ ] https://github.com/Oztechan/CCC/issues/3587
- [ ] https://github.com/Oztechan/CCC/issues/3590
- [ ] https://github.com/Oztechan/CCC/issues/3591
- [ ] https://github.com/Oztechan/CCC/issues/3592
```
