### ISSUE TITLE
Move Jobs to  Release/Debug builds for on schedule and on push

### ISSUE THREAD

**Issue by mustafaozhan** [Oztechan/CCC#3681]
```[tasklist]
### Tasks
- [ ] https://github.com/Oztechan/CCC/issues/3682
- [ ] https://github.com/Oztechan/CCC/issues/3685
- [ ] https://github.com/Oztechan/CCC/issues/3687
- [ ] https://github.com/Oztechan/CCC/issues/3689
- [ ] https://github.com/Oztechan/CCC/issues/3697
- [ ] https://github.com/Oztechan/CCC/issues/3691
- [ ] https://github.com/Oztechan/CCC/issues/3693
- [ ] https://github.com/Oztechan/CCC/issues/3695
- [ ] https://github.com/Oztechan/CCC/issues/3702
```
