### ISSUE TITLE
Refactor SEED Architecture

### ISSUE THREAD

**Issue by mustafaozhan** [Oztechan/CCC#3707]
```[tasklist]
### Tasks
- [ ] https://github.com/Oztechan/CCC/issues/3708
- [ ] https://github.com/Oztechan/CCC/issues/3712
- [ ] https://github.com/Oztechan/CCC/issues/3731
- [ ] https://github.com/Oztechan/CCC/issues/3714
- [ ] https://github.com/Oztechan/CCC/issues/3717
- [ ] https://github.com/Oztechan/CCC/issues/3719
- [ ] https://github.com/Oztechan/CCC/issues/3729
- [ ] https://github.com/Oztechan/CCC/issues/3727
- [ ] https://github.com/Oztechan/CCC/issues/3744
- [ ] https://github.com/Oztechan/CCC/issues/3745
```
