### ISSUE TITLE
Increase iOS Deployment target to 15

### ISSUE THREAD

**Issue by mustafaozhan** [Oztechan/CCC#3818]
```[tasklist]
### Tasks
- [ ] https://github.com/Oztechan/CCC/issues/3819
- [ ] https://github.com/Oztechan/CCC/issues/3821
- [ ] https://github.com/Oztechan/CCC/issues/3823
```
