### ISSUE TITLE
App Icon improvments

### ISSUE THREAD

**Issue by mustafaozhan** [Oztechan/CCC#3837]
```[tasklist]
### Tasks
- [ ] https://github.com/Oztechan/CCC/issues/3838
- [ ] https://github.com/Oztechan/CCC/issues/3841
- [ ] https://github.com/Oztechan/CCC/issues/3843
- [ ] https://github.com/Oztechan/CCC/issues/3850
- [ ] https://github.com/Oztechan/CCC/issues/3855
- [ ] https://github.com/Oztechan/CCC/issues/3854
- [ ] https://github.com/Oztechan/CCC/issues/3856
- [ ] https://github.com/Oztechan/CCC/issues/3853
```
