### ISSUE TITLE
Sheet Navigation refactoring

### ISSUE THREAD

**Issue by mustafaozhan** [Oztechan/CCC#3867]
```[tasklist]
### Tasks
- [ ] https://github.com/Oztechan/CCC/issues/3878
- [ ] https://github.com/Oztechan/CCC/issues/3880
- [ ] https://github.com/Oztechan/CCC/issues/3869
- [ ] https://github.com/Oztechan/CCC/issues/3870
- [ ] https://github.com/Oztechan/CCC/issues/3871
- [ ] https://github.com/Oztechan/CCC/issues/3872
- [ ] https://github.com/Oztechan/CCC/issues/3882
- [ ] https://github.com/Oztechan/CCC/issues/3883
- [ ] https://github.com/Oztechan/CCC/issues/3884
- [ ] https://github.com/Oztechan/CCC/issues/3888
- [ ] https://github.com/Oztechan/CCC/issues/3891
- [ ] https://github.com/Oztechan/CCC/issues/3914
- [ ] https://github.com/Oztechan/CCC/issues/3895
- [ ] https://github.com/Oztechan/CCC/issues/3897
- [ ] https://github.com/Oztechan/CCC/issues/3903
- [ ] https://github.com/Oztechan/CCC/issues/3906
- [ ] https://github.com/Oztechan/CCC/issues/3907
- [ ] https://github.com/Oztechan/CCC/issues/3910
- [ ] https://github.com/Oztechan/CCC/issues/3912
- [ ] https://github.com/Oztechan/CCC/issues/3916
```
