### ISSUE TITLE
Update Calculator Logic

### ISSUE THREAD

**Issue by mustafaozhan** [Oztechan/CCC#3918]
```[tasklist]
### Tasks
- [ ] https://github.com/Oztechan/CCC/issues/3919
- [ ] https://github.com/Oztechan/CCC/issues/3921
- [ ] https://github.com/Oztechan/CCC/issues/3923
- [ ] https://github.com/Oztechan/CCC/issues/3925
- [ ] https://github.com/Oztechan/CCC/issues/3927
- [ ] https://github.com/Oztechan/CCC/issues/3929
- [ ] https://github.com/Oztechan/CCC/issues/3931
- [ ] https://github.com/Oztechan/CCC/issues/3933
- [ ] https://github.com/Oztechan/CCC/issues/3935
```
